import type { CaseState } from './model';
const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
export function exportReport(state: CaseState): string {
  const { inspection, recommendation: rec, job, completion, verification } = state;
  const row = state.schedule.rows.find(r => r.job_id === job?.job_id);
  const section = (title: string, body: string) => `<section><h2>${title}</h2>${body}</section>`;
  const list = (items: string[]) => items.length ? `<ul>${items.map(x => `<li>${escape(x)}</li>`).join('')}</ul>` : '<p>None recorded.</p>';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>ThermalDesk ${escape(inspection.case_id)}</title><style>body{font:15px/1.6 Arial,sans-serif;max-width:900px;margin:48px auto;padding:0 24px;color:#172c3b}h1{font-size:32px}h2{font-size:18px;border-bottom:1px solid #ccd7de;padding-bottom:8px}section{break-inside:avoid;margin:28px 0}.notice{background:#fff4dc;padding:16px}table{width:100%;border-collapse:collapse;font-size:12px}td,th{text-align:left;border-bottom:1px solid #dde4e8;padding:8px;overflow-wrap:anywhere}small{color:#536577}@media print{body{margin:0}a{color:inherit}}</style></head><body>
  <small>THERMALDESK / REPAIR RECORD</small><h1>${escape(inspection.asset_id)} · ${escape(job?.status.replaceAll('_',' ') ?? 'Inspection open')}</h1>
  <p>${escape(inspection.case_id)} · ${escape(inspection.site_id)} · Revision ${state.revision}</p>
  <p class="notice">Synthetic demonstration. Recommendation analysis mode: ${escape(rec?.analysis_mode ?? 'not run')}. Plaud, parts orders, technician contact and manager messages remain simulated in this app. The local Excel update is real. Demo reviews do not certify equipment safety.</p>
  ${section('Original inspection', list(inspection.evidence.map(e => `${e.id} | ${e.kind} | ${e.asset_id ?? 'unresolved asset'} | ${e.source} (${e.mode}) | ${e.uri} | ${e.text ?? ''}`)) + '<h3>Missing inspection information</h3>' + list(inspection.missing_information))}
  ${section('Analysis findings', `<p>Status: ${escape(rec?.status ?? 'Not run')}. Recommendation: ${escape(rec ? `${rec.recommendation_id}, version ${rec.version}` : 'None')}.</p>${rec?.findings.length ? rec.findings.map(f => `<article><h3>${escape(f.id)} · ${escape(f.severity)}</h3><p>${escape(f.description)}</p><p>Source evidence: ${escape(f.evidence_ids.join(', ') || 'None linked')}</p><h4>Uncertainties</h4>${list(f.uncertainties)}</article>`).join('') : '<p>No analysis findings returned.</p>'}<h3>Information required before approval</h3>${list(rec?.missing_information ?? [])}`)}
  ${section(rec?.approval ? 'Reviewed repair scope' : 'Proposed repair scope — not approved', `<p>${escape(rec?.repair_scope ?? 'No scope recorded.')}</p>${list(rec?.parts.map(p => `${p.quantity} ${p.unit}: ${p.part_id} — ${p.approved_specification}`) ?? [])}<p>Approval: ${escape(rec?.approval ? `${rec.approval.reviewer_id}, version ${rec.approval.recommendation_version}, ${rec.approval.approved_at} (${rec.approval.mode})` : 'Not approved')}</p><p>${state.scenarioLoaded ? 'A separate synthetic repair scenario was loaded; it is not a diagnosis of the original inspection.' : ''}</p>`)}
  ${section('Appointment and workbook', `<p>Technician: ${escape(job?.booking?.technician_name ?? 'Not assigned')}. Appointment: ${escape(job?.booking?.start_at ?? 'Not booked')} — ${escape(job?.booking?.end_at ?? '')} (${escape(job?.booking?.status ?? 'none')}). Parts: ${escape(job?.parts_status ?? 'Not ordered')}.</p><p>Actual workbook row: ${escape(row ? `${row.job_id}; ${row.technician_name}; ${row.job_status}; updated ${row.last_updated_at}` : 'No verified row')}</p><p>Local file only; no Microsoft 365 sync.</p>`)}
  ${section('Action outcomes', `<table><thead><tr><th>Action</th><th>Mode / outcome</th><th>Reference and detail</th></tr></thead><tbody>${job?.actions.map(a => `<tr><td>${escape(a.action_type)}</td><td>${escape(a.mode)} / ${escape(a.status)}</td><td>${escape(a.provider_reference)}<br>${escape(a.detail)}</td></tr>`).join('') ?? ''}</tbody></table>`)}
  ${section('Completion evidence', `<p>${escape(completion?.comments ?? 'No completion evidence collected.')}</p>${list(completion?.evidence.map(e => `${e.id} | asset ${e.asset_id} | ${e.uri} | ${e.text ?? ''}`) ?? [])}${list(completion?.unresolved_items ?? [])}`)}
  ${section('Verification and remaining work', `<p>Result: ${escape(verification?.result ?? 'Not compared')}.</p>${list(verification?.checks.map(c => `${c.name}: ${c.result}. ${c.detail} Evidence: ${c.evidence_ids.join(', ')}`) ?? [])}<p>Final review: ${escape(job?.closure_review ? `${job.closure_review.reviewer_id}; ${job.closure_review.decision}; verification ${job.closure_review.verification_version}; ${job.closure_review.reviewed_at} (${job.closure_review.mode})` : 'Not accepted')}</p>${list(job?.unresolved_findings ?? [])}${list(verification?.missing_information ?? [])}`)}
  ${section('Activity history', list(state.events.map(e => `${e.at} — ${e.title} (${e.mode}). ${e.detail}`)))}
  </body></html>`;
}
