/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ThermalDeskExchangeEnvelopeV1 =
  | {
      kind: "InspectionPackage";
      data: InspectionPackage;
    }
  | {
      kind: "Recommendation";
      data: Recommendation;
    }
  | {
      kind: "RepairJob";
      data: RepairJob;
    }
  | {
      kind: "CompletionEvidence";
      data: CompletionEvidence;
    }
  | {
      kind: "VerificationDraft";
      data: VerificationDraft;
    }
  | {
      kind: "ActionReceipt";
      data: ActionReceipt;
    };
export type IntegrationMode = "live" | "sandbox" | "simulated";
export type Recommendation = {
  schema_version: "1.0";
  case_id: string;
  site_id: string;
  asset_id: string;
  recommendation_id: string;
  inspection_id: string;
  version: number;
  status: "draft" | "needs_information" | "approved" | "rejected";
  findings: Finding[];
  repair_scope: string;
  parts: Part[];
  missing_information: string[];
  approval: Approval | null;
  analysis_mode: IntegrationMode;
  created_at: string;
};

export interface InspectionPackage {
  schema_version: "1.0";
  case_id: string;
  site_id: string;
  asset_id: string;
  inspection_id: string;
  evidence: Evidence[];
  observations: Observation[];
  missing_information: string[];
  created_at: string;
}
export interface Evidence {
  id: string;
  kind: "thermal_image" | "photo" | "transcript" | "note" | "measurement" | "receipt" | "equipment_history";
  asset_id: string | null;
  source: "plaud" | "upload" | "import" | "synthetic";
  mode: IntegrationMode;
  uri: string;
  captured_at: string | null;
  text?: string;
  provider_record_id?: string;
  segments?: {
    id: string;
    text: string;
    start_seconds?: number;
    end_seconds?: number;
    speaker?: string;
  }[];
}
export interface Observation {
  id: string;
  text: string;
  evidence_ids: string[];
  segment_ids: string[];
  needs_review: boolean;
}
export interface Finding {
  id: string;
  description: string;
  evidence_ids: string[];
  severity: "unassessed" | "low" | "medium" | "high";
  uncertainties: string[];
}
export interface Part {
  part_id: string;
  approved_specification: string;
  quantity: number;
  unit: string;
  requires_specification_review: boolean;
}
export interface Approval {
  reviewer_id: string;
  recommendation_version: number;
  approved_at: string;
  mode: IntegrationMode;
}
export interface RepairJob {
  schema_version: "1.0";
  case_id: string;
  site_id: string;
  asset_id: string;
  job_id: string;
  recommendation_id: string;
  recommendation_version: number;
  state_version: number;
  status:
    | "planning"
    | "awaiting_authorization"
    | "coordinating"
    | "scheduled"
    | "in_progress"
    | "awaiting_verification"
    | "closed"
    | "blocked"
    | "cancelled";
  authority: Authority | null;
  parts_status: "not_required" | "not_ordered" | "ordered" | "available" | "delayed";
  booking: Booking | null;
  actions: ActionReceipt[];
  unresolved_findings: string[];
  closure_review: ClosureReview | null;
  updated_at: string;
}
export interface Authority {
  authority_id: string;
  mode: IntegrationMode;
  currency: string;
  max_total_minor: number;
  allowed_actions: (
    | "supplier_quote"
    | "parts_order"
    | "technician_contact"
    | "booking"
    | "schedule_sync"
    | "manager_notify"
    | "follow_up"
  )[];
  expires_at: string;
}
export interface Booking {
  technician_id: string;
  technician_name: string;
  start_at: string;
  end_at: string;
  status: "proposed" | "confirmed" | "cancelled";
  confirmation_action_id: string | null;
}
export interface ActionReceipt {
  action_id: string;
  job_id: string;
  action_type:
    | "supplier_quote"
    | "parts_order"
    | "technician_contact"
    | "booking"
    | "schedule_sync"
    | "manager_notify"
    | "follow_up";
  idempotency_key: string;
  mode: IntegrationMode;
  status: "requested" | "pending" | "confirmed" | "failed" | "not_configured";
  provider_reference: string | null;
  evidence_ids: string[];
  detail: string;
  recorded_at: string;
}
export interface ClosureReview {
  reviewer_id: string;
  verification_id: string;
  verification_version: number;
  completion_version: number;
  recommendation_version: number;
  decision: "approve_closure" | "keep_open";
  reviewed_at: string;
  mode: IntegrationMode;
}
export interface CompletionEvidence {
  schema_version: "1.0";
  case_id: string;
  site_id: string;
  asset_id: string;
  completion_id: string;
  job_id: string;
  version: number;
  technician_id: string;
  reported_status: "complete" | "incomplete" | "unknown";
  comments: string;
  evidence: Evidence[];
  unresolved_items: string[];
  created_at: string;
}
export interface VerificationDraft {
  schema_version: "1.0";
  case_id: string;
  site_id: string;
  asset_id: string;
  verification_id: string;
  job_id: string;
  version: number;
  recommendation_version: number;
  completion_id: string;
  completion_version: number;
  result: "ready_for_review" | "needs_information" | "mismatch";
  checks: {
    name: string;
    result: "pass" | "fail" | "unknown";
    evidence_ids: string[];
    detail: string;
  }[];
  missing_information: string[];
  analysis_mode: IntegrationMode;
  created_at: string;
}
